version: "3.7"
services:
  dind:
    image: docker:24.0.2-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-certs:/certs
      - jenkins-data:/var/jenkins_home

  jenkins:
    build: .
    image: my-jenkins:dind
    environment:
      DOCKER_HOST: tcp://dind:2375
      DOCKER_TLS_CERTDIR: ""
    depends_on:
      - dind
    ports:
      - "8082:8080"
      - "50002:50000"
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  dind-certs:
  jenkins-data:
