# Dockerfile.3 - tester
FROM golang:1.20-alpine
LABEL maintainer="Twoje Imię <email@domena>"

WORKDIR /app
RUN apk update && apk add --no-cache make

VOLUME ["/app/input", "/app/output"]

# Uruchamia testy na kodzie w /app/input
CMD ["sh", "-c", "cd /app/input && make test 2>&1 | tee /app/output/test.log"]