# Dockerfile.2 - builder
FROM golang:1.20-alpine
LABEL maintainer="Twoje Imię <email@domena>"

WORKDIR /app
RUN apk update && apk add --no-cache git make

# Utworzenie katalogów i punktów montowania
RUN mkdir -p input output
VOLUME ["/app/input", "/app/output"]

# Klonowanie kodu do input
RUN git clone https://github.com/Rafallost/snake-game.git input

# Domyślna komenda: budowa i zapis logów
CMD ["sh", "-c", "cd input && go build -v -o /app/output/snake 2>&1 | tee /app/output/build.log"]