version: "3.8"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.2
    image: snake-builder:1.0
    volumes:
      - ./repo_input:/app/input   # kod z workspace
      - ./repo_output:/app/output # miejsce na logi i artefakty

  tester:
    build:
      context: .
      dockerfile: Dockerfile.3
    image: snake-tester:1.0
    depends_on:
      - builder
    volumes:
      - ./repo_input:/app/input
      - ./repo_output:/app/output